'''
# Extract artists
artists = df["Artist Name(s)"].str.split(", ").explode().unique().tolist()

# Extract genres
genres = df["Artist Genres"].str.split(",").explode().str.strip().unique().tolist()
'''

all_artists = [
 'The KLF',
 'Pitbull',
 'Britney Spears',
 'The Kinks',
 'The Rolling Stones',
 'Fleetwood Mac',
 'benny blanco',
 'Halsey',
 'Khalid',
 'Elton John',
 'Foreigner',
 'Shawn Mendes',
 'Run–D.M.C.',
 'Jason Nevins',
 '3 Doors Down',
 'The Monkees',
 'Wings',
 'Ed Sheeran',
 'Pussycat',
 'Nathaniel',
 'Buzz Clifford',
 'Tina Charles',
 'Glee Cast',
 'Gwyneth Paltrow',
 'The Soup Dragons',
 'Junior Reid',
 'Sam Smith',
 'Suzi Quatro',
 'Troye Sivan',
 'KC & The Sunshine Band',
 'Hey Monday',
 'P!nk',
 'Ariana Grande',
 'Marty Wilde',
 'Brenda Lee',
 'Deni Hines',
 'T. Rex',
 'Belinda Carlisle',
 'John Mellencamp',
 'Miley Cyrus',
 'Birdy',
 'Zedd',
 'Hayley Williams',
 'Red Hot Chili Peppers',
 'Queen',
 'Warumpi Band',
 'Craig David',
 'Monte Video',
 'Jarryd James',
 'Julia Stone',
 'C.W. McCall',
 'Manfred Mann',
 'Amy Winehouse',
 'Conor Maynard',
 'Ne-Yo',
 'Timbaland',
 'Gotye',
 'Kimbra',
 'Yusuf / Cat Stevens',
 'The Easybeats',
 'Stevie Wonder',
 'Petula Clark',
 'Eminem',
 'Sugababes',
 'Zay Hilfigerrr',
 'Zayion McCall',
 'Lady Gaga',
 'Madness',
 'Dr. Hook',
 'Joe Jones',
 'Smash Mouth',
 'Jordie Ireland',
 'Ava Hayz',
 'Tom Cochrane',
 'Dua Lipa',
 'Backstreet Boys',
 'Selena Gomez',
 'Sean Paul',
 'Flo Rida',
 'Akon',
 'Kasey Chambers',
 'P.M. Dawn',
 'Swedish House Mafia',
 'John Martin',
 'Vanessa Williams',
 'Labrinth',
 'Emeli Sandé',
 'The Beach Boys',
 'Sia',
 'Snoop Dogg',
 'David Guetta',
 'Giorgio Tuinfort',
 'Frederic Riesterer',
 'Spandau Ballet',
 'Alessia Cara',
 'Olly Murs',
 'David Jones',
 'Kim Wilde',
 'Travie McCoy',
 'Tate McRae',
 'Guy Sebastian',
 'Justin Bieber',
 'Big Sean',
 'Mandy Moore',
 'AlunaGeorge',
 'Popcaan',
 'Shakira',
 'Rihanna',
 'Johnny Cash',
 'June Carter Cash',
 'Youth Group',
 'Carole King',
 'Bruno Mars',
 'Meco',
 'Ted Mulry Gang',
 'Capital Cities',
 'Pendulum',
 'The Connells',
 'Spin Doctors',
 'Toni Braxton',
 'Dannii Minogue',
 'Cody Simpson',
 'Bryan Ferry',
 'James Arthur',
 'Stafford Brothers',
 'Lil Wayne',
 'Christina Milian',
 'Mariah Carey',
 'Trey Lorenz',
 'Little Mix',
 'Powfu',
 'beabadoobee',
 'Taylor Henderson',
 'Samantha Jade',
 'Nitty',
 'Ja Rule',
 'Ashanti',
 'Prince',
 'The Human League',
 'Mark Holden',
 'Melissa Manchester',
 'Bryan Adams',
 'Bee Gees',
 'Sandi Thom',
 'Neil Young',
 'Murphy Lee',
 'Nelly',
 'Diddy',
 'Bros',
 'Wiz Khalifa',
 'Charlie Puth',
 'Heavy D & The Boyz',
 'Aaron Hall',
 'The Weeknd',
 'Billy Thorpe & The Aztecs',
 'Aretha Franklin',
 'Betty Boo',
 'Neil Diamond',
 'Blondie',
 'Monica',
 'Foo Fighters',
 'Train',
 'OneRepublic',
 'Frijid Pink',
 'The Chemical Brothers',
 'Fern Kinney',
 'The Bells',
 "Scandal'us",
 "The B-52's",
 'Colbie Caillat',
 'Dami Im',
 'Chris Stapleton',
 'R. Kelly',
 'Jessica Mauboy',
 'Roxy',
 'Babyface',
 'Kenny G',
 'Shalamar',
 'Ultra Naté',
 'Iggy Azalea',
 'Paul McCartney',
 'Papa Roach',
 'Bobby Lewis',
 'Cold Chisel',
 'Whitney Houston',
 'Afroman',
 'Dave Mills',
 'JX',
 'Violent Femmes',
 'The Chainsmokers',
 'Amy Shark',
 'Evermore',
 'Sub Sub',
 'Melanie Williams',
 'Soul Asylum',
 'Sarah Blasko',
 'Five',
 'Steve Mac',
 'Stargate',
 'Cutfather & Joe',
 'Montell Jordan',
 'Nitty Gritty Dirt Band',
 'Scott McKenzie',
 'Taylor Swift',
 'Swing Out Sister',
 'Kygo',
 'Conrad Sewell',
 'Wynter Gordon',
 "Richard O'Brien",
 'Patricia Quinn',
 'Nell Campbell',
 'Michael Jackson',
 'Janet Jackson',
 'Taxiride',
 'Peter\\',
 'Paul and Mary',
 'Maroon 5',
 'Imagine Dragons',
 'Daniel Powter',
 'John Farnham',
 'Nick Jonas',
 'Melanie C',
 'Lisa "Left Eye" Lopes',
 'Kelly Rowland',
 'The Script',
 'Nat King Cole',
 'Powderfinger',
 'Mýa',
 'ZAYN',
 'Peter And Gordon',
 'Major Lazer',
 'MØ',
 'DJ Snake',
 'The Fray',
 'Eternal',
 'Bebe Winans',
 'Jerry Harrison',
 'Jackie Wilson',
 'Elvis Presley',
 'Martin Solveig',
 'Dragonette',
 'RÜFÜS DU SOL',
 'Lil Nas X',
 'Dzeko & Torres',
 'Sarah McLeod',
 'One Direction',
 'B.J. Thomas',
 'Jimmy Barnes',
 'Travis Scott',
 'Kesha',
 'The Mamas & The Papas',
 'Craig McLachlan;Check 1-2',
 'The Edgar Winter Group',
 'Jasmine Thompson',
 'Chaka Demus & Pliers',
 'Jack Radics',
 'The Taxi Gang',
 'Havana Brown',
 'A1',
 'Kiki Dee',
 'Pet Shop Boys',
 'Ricky Martin',
 'John Williamson',
 'Boom Crash Opera',
 'Melanie',
 'The Belle Stars',
 'Calvin Harris',
 'Dean Lewis',
 'Usher',
 'Lil Jon',
 'Ludacris',
 'Coldplay',
 'Starship',
 'The 1975',
 'Kylie Minogue',
 'Frankie Valli',
 'Sherbet',
 'Anita Bryant',
 'The 5th Dimension',
 'Mike + The Mechanics',
 'ABBA',
 'En Vogue',
 'The Presets',
 'Tom Petty and the Heartbreakers',
 'All Time Low',
 'Demi Lovato',
 'blackbear',
 'Bowling For Soup',
 'will.i.am',
 'The Cure',
 'Tokyo Ghetto Pussy',
 'The Browns',
 'Matchbox Twenty',
 'Stan Walker',
 'Peter Frampton',
 'Alec Benjamin',
 'Michael Bublé',
 'Meghan Trainor',
 'Judy Collins',
 'Jamie Foxx',
 'Timomatic',
 'Anne-Marie',
 'Niall Horan',
 'Luca Schreiner',
 'The Shadows',
 'Alanis Morissette',
 'Normie Rowe & The Playboys',
 'Faron Young',
 'Joan Jett & the Blackhearts',
 'Mental As Anything',
 'Bon Jovi',
 'DHT',
 'Edmee',
 'Furious F.',
 'Do Re Mi',
 'Kate Miller-Heidke',
 'Bonnie Tyler',
 'Canned Heat',
 'Alicia Keys',
 'Nicki Minaj',
 'Phillip Phillips',
 'The Righteous Brothers',
 'Natalie Bassingthwaighte',
 'Rocky Burnette',
 'Eurythmics',
 'Annie Lennox',
 'Dave Stewart',
 'Tears For Fears',
 'Boyz II Men',
 'Erasure',
 'Peter Allen',
 'Avril Lavigne',
 'HERBIE',
 'House Of Pain',
 'The Galvatrons',
 'Bebe Rexha',
 'Doja Cat',
 'Stone Temple Pilots',
 'Sheppard',
 'Flowers',
 'Winger',
 'Los Del Rio',
 'Oliver',
 'Korn',
 'Eve',
 'Gwen Stefani',
 'Bastille',
 'Ella Henderson',
 'Gale Garnett',
 'Marcy Playground',
 'Simple Plan',
 'Eddie Money',
 'Roddy Ricch',
 'Derek',
 'Jason Derulo',
 'PSY',
 'Clean Bandit',
 'iann dior',
 'Caramel Blue',
 'Darude',
 'Colleen Hewett',
 'The Temptations',
 'Charli XCX',
 'Right Said Fred',
 'Inner Circle',
 'Billy Joel',
 'Brian Cadd',
 'Madonna',
 'Ellie Goulding',
 'Killing Heidi',
 'Gin Blossoms',
 'Simon & Garfunkel',
 'Alice Cooper',
 'Colin Hay',
 'Harry Styles',
 'Vance Joy',
 'Beyoncé',
 'Coolio',
 '40 Thevz',
 'The Zombies',
 'Culture Club',
 'Olivia Newton-John',
 'The Rubens',
 'Ray Parker Jr.',
 'Betty Who',
 'Live',
 'Eric Carmen',
 'Fabolous',
 'Mike Shorey',
 "Lil' Mo",
 'Silentó',
 'Nickelback',
 'No Mercy',
 'Lauv',
 'Conan Gray',
 'Travis',
 'Billy Idol',
 'Jonas Brothers',
 'Busta Rhymes',
 'Flipmode Squad',
 'Lindsay Lohan',
 'Qwote feat. Pitbull & Lucenzo',
 "Destiny's Child",
 'Julia Michaels',
 'Frank Sinatra',
 'Count Basie',
 'Tiki Taane',
 'Noah Kahan',
 'Cher',
 'Robert Palmer',
 'David Lee Roth',
 'Kool & The Gang',
 'Teddy Cream',
 'Szabo',
 'Daryl Braithwaite',
 'Madasun',
 'Creedence Clearwater Revival',
 'Gym Class Heroes',
 'Neon Hitch',
 'Jay & The Americans',
 'Barry White',
 'Skyhooks',
 'The Madden Brothers',
 'BZ',
 'Joanne',
 'Culture Beat',
 'Marques Houston',
 'Julie Covington',
 'Andrew Lloyd Webber',
 'Tim Rice',
 'Jamie Lawson',
 'The Preatures',
 'The Fureys',
 'Davey Arthur',
 'Nancy Sinatra',
 'Lee Hazlewood',
 'The Fortunes',
 'Lizzo',
 'Garrett Kato',
 'Cheap Trick',
 'Route 94',
 'Jess Glynne',
 'Dead Or Alive',
 'Sigma',
 'Sofi Tukker',
 "Colby O'Donis",
 '1927',
 'Lou Rawls',
 'The Clovers',
 'Joe',
 'Air Supply',
 'The Offspring',
 'Triple X',
 'Nick Skitz',
 'Westlife',
 'Black Eyed Peas',
 'Kate Bush',
 'Silverchair',
 'George Michael',
 'The Duprees',
 'Michael Bolton',
 'Kim Cesarion',
 'Lorde',
 'Pandora',
 'San Cisco',
 'The Swingers',
 'Justin Timberlake',
 'Tracy Chapman',
 'Eskimo Joe',
 'Natasha Bedingfield',
 'Kate Nash',
 'Ricki-Lee',
 'The Stranglers',
 '2Pac',
 'The Notorious B.I.G.',
 'Kasabian',
 'TV Rock feat. Seany B',
 'Ali Gatie',
 'Idina Menzel',
 'Daddy Cool',
 'Wretch 32',
 'Example',
 'Ms. Lauryn Hill',
 'Selwyn',
 'U2',
 'George Ezra',
 'Shaggy',
 'Brian & Tony Gold',
 'The Hollies',
 'Felix',
 'T.I.',
 'Paul Woolford',
 'Amber Mark',
 'Connie Francis',
 'Ou Est Le Swimming Pool',
 'Mashd N Kutcher',
 'Jam & Spoon',
 'Plavka',
 'Jennifer Lopez',
 'LL COOL J',
 'Kris Kross',
 'Alan Walker',
 'The Civil Wars',
 'John Fogerty',
 'Atomic Kitten',
 'Josh Pyke',
 'Hockey',
 'CAKE',
 'Christina Perri',
 'Richard Marx',
 'Shania Twain',
 'Kanye West',
 'Macklemore & Ryan Lewis',
 'Mary Lambert',
 'Savage Garden',
 'Floyd Cramer',
 'Kenny Rogers & The First Edition',
 'Lenny Kravitz',
 'A Flock Of Seagulls',
 'Nana Mouskouri',
 'Linkin Park',
 'Cilla Black',
 'Of Monsters and Men',
 '360',
 'Gossling',
 'John Travolta',
 'Years & Years',
 'Anton',
 'DJ Ötzi',
 'Boyzone',
 'Enrique Iglesias feat. Pitbull',
 'Blake Shelton',
 'Louis Tomlinson',
 'Marshmello',
 'Racey',
 'Cyndi Lauper',
 'The Cranberries',
 'Autumn',
 'New Kids On The Block',
 'Hunters & Collectors',
 'The Police',
 'Divinyls',
 'Dee Clark',
 'Normani',
 'Blood\\',
 'Sweat & Tears',
 'September',
 'Merril Bainbridge',
 'Weezer',
 'The White Stripes',
 'Rogue Traders',
 'BOYS LIKE GIRLS',
 'Al Martino',
 'Pink Floyd',
 'Liv Maessen',
 'Alex Lloyd',
 'Jeannie C. Riley',
 'Jessica Simpson',
 'The Loved Ones',
 'Massive Attack',
 'Yazoo',
 'Hoodoo Gurus',
 'Everlast',
 'Hailee Steinfeld',
 'Alesso',
 'Florida Georgia Line',
 'WATT',
 'Crowded House',
 'Hook N Sling',
 'Johnny Tillotson',
 'Avicii',
 'Calum Scott',
 'Gyroscope',
 'Flash and the Pan',
 'Donna Summer',
 'Daughtry',
 'Jason Mraz',
 'Underworld',
 'Johnny Burnette',
 'Bob Dylan',
 'Creed',
 'Peaches',
 'Bobby Darin',
 'The Sensations',
 'Crash Test Dummies',
 'Paloma Faith',
 "Herman's Hermits",
 'Thompson Twins',
 'Gene McDaniels',
 'Traffic',
 'Seether',
 'B.o.B',
 'Besomorph',
 'Lucifer',
 'The Pointer Sisters',
 'Katy Perry',
 'Ram Jam',
 'Julian Casablancas',
 'Maty Noyes',
 'Donovan',
 'Nico & Vinz',
 'Kid Ink',
 'David Franj',
 'Billie Eilish',
 'Lupe Fiasco',
 'Matthew Santos',
 'Brandi Carlile',
 'La Roux',
 'Rick James',
 'Ciara',
 'Nicolette Larson',
 'Adele',
 'Julio Iglesias',
 'Willie Nelson',
 'Bill Medley',
 'Jennifer Warnes',
 'Camille Jones',
 'Fedde Le Grand',
 'Rosie & The Originals',
 'Delta Goodrem',
 'Redgum',
 'Eruption',
 'The Screaming Jets',
 'The Reels',
 'Adam & The Ants',
 'KISS',
 'Del Amitri',
 'Green Day',
 'Peter McCann',
 'Sheena Easton',
 'The Crystals',
 'Maxi Priest',
 'John Gallen',
 'Metro Station',
 'Rudimental',
 'Will Heard',
 'The Angels',
 'The Who',
 'New Order',
 'Jawsh 685',
 'Liberty X',
 'Irene Cara',
 'Mary J. Blige',
 'Eliza Doolittle',
 'Tommy Tutone',
 'Ricky Nelson',
 'Bob Fisher',
 'The Pussycat Dolls',
 'Christina Aguilera',
 'JP Saxe',
 'Falco',
 'Rob Mills',
 'Rixton',
 'Tina Cousins',
 'Kenny Loggins',
 "Why Don't We",
 'Incubus',
 'Empire of the Sun',
 'Journey',
 'Roger Glover',
 'Ronnie James Dio',
 'Meat Loaf',
 'LEN',
 'Drake',
 'Lil Durk',
 'Q-Tip',
 'Joni Mitchell',
 'Johnny Crawford',
 'Baby Animals',
 'Arrested Development',
 'S Club 7',
 'G-Eazy',
 'The All-American Rejects',
 'The Bureau',
 'Masked Wolf',
 'Al Stewart',
 'Todd Rundgren',
 'Disclosure',
 'The Sandpipers',
 'Jason Donovan',
 'Rita Ora',
 'Lana Del Rey',
 'Tony Christie',
 'Brian McFadden',
 'Peter Andre',
 'Stevie Nicks',
 'Bazzi',
 'Chumbawamba',
 'Men At Work',
 "Shakin' Stevens",
 'Wham!',
 'R3HAB',
 'Maurice Williams & The Zodiacs',
 'Louis Armstrong',
 'Murry Kellum',
 'Leona Lewis',
 'Duran Duran',
 'David Bowie',
 'Kendrick Lamar',
 'Gary U.S. Bonds',
 'Jenny Morris',
 'Caesars',
 'David Dundas',
 'Jimmy Soul',
 'Noah And The Whale',
 'Tove Styrke',
 'Led Zeppelin',
 'Kelly Clarkson',
 'Mark Ronson',
 'Kid Rock',
 'Martika',
 'Van McCoy & The Soul City Symphony',
 'Marvin Gaye',
 'Tammi Terrell',
 'Migos',
 'Buddy Holly',
 'NEWBEATS',
 'Florence + The Machine',
 'M.I.A.',
 'Hot Chocolate',
 'B*Witched',
 'Kisschasy',
 "Lil' Kim",
 'Ruby Velle & The Soulphonics',
 'Slade',
 'Cosima De Vito',
 'Jessie J',
 'C & C Factory',
 'Dire Straits',
 'Chris Andrews',
 'Noah Cyrus',
 'Digital Farm Animals',
 'Juliander',
 'Wyclef Jean',
 'Claudette Ortiz',
 'Chase & Status',
 'Liam Bailey',
 'Kenny',
 'Tommy Roe',
 'Roxette',
 'Vangelis',
 'INXS',
 'Urge Overkill',
 'Paramore',
 'Miguel',
 'Ned Miller',
 'Bobby McFerrin',
 "Australia's Own Jigsaw",
 'Wallows',
 'Clairo',
 'Maureen McGovern',
 'Dusty Springfield',
 'Tom Petty',
 'Katrina & The Waves',
 "Plain White T's",
 'Ohio Players',
 'Billy J. Kramer',
 'The Dakotas',
 'The Sundance Kids',
 'Tones And I',
 'Eddie Rabbitt',
 'Billie Piper',
 'Gorillaz',
 'Rae Sremmurd',
 'Gucci Mane',
 'Mabel',
 'Steve Miller Band',
 'Wa Wa Nee',
 'John Paul Young',
 'Jon English',
 'The Jackson 5',
 'The Beatles',
 'The Mighty Mighty Bosstones',
 'WILLOW',
 'Lionel Richie',
 'Mötley Crüe',
 'Hot Chelle Rae',
 'Kings of Leon',
 'Electric Light Orchestra',
 'Sting',
 'Damien Leith',
 'Lee Harding',
 'PEZ',
 'Daft Punk',
 'Daniel Bedingfield',
 'Missy Elliott',
 'Zara Larsson',
 'Sophie B. Hawkins',
 'Donny Osmond',
 'Leo Sayer',
 'Short Stack',
 'Herb Alpert & The Tijuana Brass',
 'Sam Feldt',
 'fun.',
 'Alphaville',
 'Kleerup',
 'Robyn',
 'Mickey Gilley',
 "Sinéad O'Connor",
 'Gloria Estefan',
 'Kulcha',
 'Karen Knowles',
 'Chris Willis',
 'Fergie',
 'LMFAO',
 'Roy Orbison',
 'Justice Crew',
 'Daryl Hall & John Oates',
 'John Denver',
 'Something For Kate',
 'Dimples D.',
 'Ben Liebrand',
 'Radiohead',
 'Eddie Hodges',
 'Cornershop',
 'Enrique Iglesias',
 'Lil Dicky',
 'Chris Brown',
 'Kaz James',
 'Macy Gray',
 'Alan Jackson',
 'Jimmy Buffett',
 '5 Seconds of Summer',
 'Sheryl Crow',
 'Starsailor',
 'AJR',
 'The Goo Goo Dolls',
 'Shouse',
 'Susan Raye',
 'Santana',
 'The Product G&B',
 'The Crests',
 'The Bangles',
 '2 Chainz',
 'The Knickerbockers',
 'AFROJACK',
 'Nayer',
 'Roger Whittaker',
 'Lady A',
 'S.O.A.P.',
 'The DeFranco Family',
 'Tony DeFranco',
 'SWV',
 'City Spud',
 'Tom Jones',
 'Peaches & Herb',
 'Sugar Ray',
 'Jimi Hendrix',
 'Macklemore',
 'Ryan Lewis',
 'Grandmaster Melle Mel',
 'Grandmaster Caz',
 'Kool Moe Dee',
 'Eric Nally',
 'The Simpsons',
 'Stone Poneys',
 'Linda Ronstadt',
 'Busby Marou',
 'Nuka',
 'The Living End',
 'Norah Jones',
 'Robbie Williams',
 'Pablo Cruise',
 'BloodPop®',
 'John Mayer',
 'Az Yet',
 'The Fireballs',
 'Exile',
 'The J. Geils Band',
 'Sparkadia',
 'Dizzee Rascal',
 "Gilbert O'Sullivan",
 'The Cowsills',
 'Armin van Buuren',
 'Trevor Guthrie',
 'The Killers',
 'GATC',
 'Austin Mahone',
 'SAYGRACE',
 'Cheat Codes',
 'Scribe',
 'Little River Band',
 'Herbie Hancock',
 'Timi Yuro',
 'Children Collide',
 'ACRAZE',
 'Cherish',
 'Céline Dion',
 'Groove Armada',
 "Gram'ma Funk",
 'Brendon Urie',
 'Aerosmith',
 'Neon Trees',
 'Chicago',
 'GABRIELLE',
 'M83',
 "I'm Talking",
 'Holly Valance',
 'Regurgitator',
 'The Dream Academy',
 'Tiësto',
 'Emily Hackett',
 'Will Anderson',
 'Del Shannon',
 'Tonic',
 'Heart',
 'Average White Band',
 'Kajagoogoo',
 'NEIKED',
 'Mae Muller',
 'Polo G',
 'RAYE',
 '070 Shake',
 'Gramma Funk',
 'Kiesza',
 'The Black Keys',
 'SZA',
 'Metallica',
 'Jonas Blue',
 'Jack & Jack',
 'Camila Cabello',
 'DaBaby',
 'F.R. David',
 'The Whitlams',
 "Guns N' Roses",
 'Custard',
 'Billy Ray Cyrus',
 'Joe Dolan',
 '4 P.M.',
 'Outkast',
 'The Vamps',
 'Martin Jensen',
 'Jimmy Gilmer',
 'Sam Cooke',
 'Rita Coolidge',
 'Sammy Davis Jr.',
 'Grinspoon',
 'Isaiah Firebrace',
 'The S.O.S Band',
 'Bill Pursell',
 'BENEE',
 'Gus Dapperton',
 'Lulu',
 'Babylon Zoo',
 'Australian Crawl',
 'Tiga',
 'Gavin DeGraw',
 'Billy Ocean',
 'Cutting Crew',
 'Natalia Kills',
 'The Sylvers',
 'Clout',
 'Optacure',
 'Kevin Rudolf',
 'Birdman',
 'Jay Sean',
 'Blxst',
 'Bino Rideaux',
 'Peter Cetera',
 'Amy Grant',
 'Angry Anderson',
 'Regard',
 'James Brown & The Famous Flames',
 'Wang Chung',
 'Rod Stewart',
 'Ray Charles Orchestra',
 'D:Ream',
 'William Singe',
 'Pharoahe Monch',
 'Cyrus Villanueva',
 'The Verve',
 'Faith Hill',
 'The Veronicas',
 'Hanson',
 'Vader the Villin',
 'Will Smith',
 'Peter Shelley',
 'Don Henley',
 'ponders',
 'Mason Parks',
 'J. Holiday',
 'George McCrae',
 'Geri Halliwell',
 'Florence Welch',
 'The Potbelleez',
 'A.B. Logic',
 'Sammi Elston',
 'Bluejuice',
 'No Doubt',
 'U.S.A. For Africa',
 'Janelle Monáe',
 'Shaun Cassidy',
 'Peters & Lee',
 'Bronski Beat',
 'Teflon Hustle Don',
 'H2O',
 'Ian Moss',
 'TLC',
 'Redfoo',
 'Ashlee Simpson',
 'Corey Hart',
 'Barbara Lewis',
 'Trini Lopez',
 'Sabrina Carpenter',
 'Sam Winston',
 'The Moody Blues',
 'Billy Vaughn',
 'After 7',
 'LANY',
 'Burl Ives',
 'Diana Ross',
 'DNCE',
 'Faith No More',
 'McFly',
 'Little Birdy',
 'Human Nature',
 'Five For Fighting',
 'The Stone Canyon Band',
 'Far East Movement',
 'Franz Ferdinand',
 'Three Dog Night',
 'Estelle',
 'Limp Bizkit',
 'The Look',
 'Midnight Oil',
 'BANNERS',
 'Jona Lewie',
 'Nick Lachey',
 'Arthur Conley',
 'The Aston Shuffle',
 'The Toys',
 'Michael Sembello',
 'Anna Kendrick',
 'Salt-N-Pepa',
 'The Keymakers',
 'End Of Fashion',
 'Renee Geyer',
 'Collective Soul',
 'Gabby Barrett',
 'Silk City',
 'Diplo',
 'James Morrison',
 'Hilary Duff',
 'Bliss n Eso',
 'Gavin James',
 '*NSYNC',
 'lovelytheband',
 'John Newman',
 'Donna Fargo',
 'Split Enz',
 'Bounty Killer',
 'The Surfaris',
 'Kelly Osbourne',
 'Cathy Dennis',
 'Tone-Loc',
 'Cascada',
 'The Bloody Beetroots',
 'Steve Aoki',
 'Sigala',
 'Ella Eyre',
 'Jimmy Eat World',
 'Paul Kelly',
 'The Messengers',
 'Bay City Rollers',
 'Bucks Fizz',
 'The Mixtures',
 'GANGgajang',
 'Stefflon Don',
 'Player 1',
 'Yothu Yindi',
 'Dzeko',
 'Preme',
 'Post Malone',
 'Cliff Richard & The Shadows',
 'Earth\\',
 'Wind & Fire',
 'The Emotions',
 'Bob The Builder',
 'Karmin',
 'Taio Cruz',
 'Johnny Rivers',
 'Justin Jesso',
 'Melissa Etheridge',
 'Counting Crows',
 'Vanessa Carlton',
 'Uncle Kracker',
 'Semisonic',
 'Roberta Flack',
 'Paul Carrack',
 'Tiffany',
 'Arrow',
 'E^ST',
 'The Kite String Tangle',
 'Bridgette Amofah',
 'Belle Epoque',
 'MAGIC!',
 'Barbra Streisand',
 'Big Audio Dynamite',
 'Olivia Rodrigo',
 'Fall Out Boy',
 'Billy Joe Royal',
 'John Rowles',
 '50 Cent',
 'Olivia',
 'Evanescence',
 'Vanessa Amorosi',
 'Reel 2 Real',
 'The Mad Stuntman',
 'Alex Natale DJ',
 'Visnadi',
 'Brando',
 'Marv Johnson',
 'New Vaudeville Band',
 'Aloe Blacc',
 'Enya',
 'Cedric Gervais',
 'Carlos Cid',
 'Jordin Sparks',
 'Reef',
 'Pixie Lott',
 'Bush',
 'Hole',
 'Adam Levine',
 'Freestylers',
 'Adam Lambert',
 'Lost Frequencies',
 'Bun B',
 'Slim Thug',
 'Jeezy',
 'The Rembrandts',
 'Brook Benton',
 'Real McCoy',
 'Boston',
 'Eurogliders',
 'Zhané',
 'Maggie Lindemann',
 'CADE',
 'Slim Dusty',
 'Ronan Keating',
 'Matt Monro',
 'Nyla',
 'Fuse ODG',
 'Budjerah',
 'London Grammar',
 'Anthony Callea',
 'Mario',
 'America',
 'George Martin',
 'George Harrison',
 'Edison Lighthouse',
 'Jack Johnson',
 'Partners In Kryme',
 'Blu Cantrell',
 'Scorpions',
 'Mis-Teeq',
 'Jody Miller',
 'Panic! At The Disco',
 'Rojdar',
 'Shannon Noll',
 'Tina Turner',
 'Daniel Merriweather',
 'Eddie Miller',
 'Robert Yount',
 'Dub Williams',
 'Engelbert Humperdinck',
 'Andy Kim',
 'Depeche Mode',
 'Haircut 100',
 'Andrea True Connection',
 'Broken Bells',
 'French Montana',
 'Swae Lee',
 'Pearl Jam',
 'White Lies',
 'David Soul',
 'Jet',
 'Paul & Paula',
 'Boy Meets Girl',
 'blink-182',
 'MC Hammer',
 'Martin Garrix',
 'Clinton Kane',
 'Young Divas',
 'Randy & The Rainbows',
 'Fischer-Z',
 'Simply Red',
 'Andy Williams',
 'Barry Crocker',
 'G.R.L.',
 'N.E.R.D',
 'Aqua',
 'Jack White',
 'Chubby Checker',
 'Peter Gabriel',
 'Patrick Hernandez',
 'Mr. Probz',
 'Sister Hazel',
 'Marc E. Bassy',
 'Wayne Fontana',
 'Ava Max',
 'Daniel Boone',
 'TQ',
 'The Crickets',
 'Bobby Brown',
 'James Reyne',
 'Breakfast Club',
 'The Cuff Links',
 'Parson James',
 'Birds Of Tokyo',
 'Len Barry',
 'Rotimi',
 'Snow Patrol',
 'The Edwin Hawkins Singers',
 'Fatboy Slim',
 'Keith Urban',
 'Vera Blue',
 'Shai',
 'Bill Appleberry',
 'Kid Cudi',
 'Crookers',
 'Alexis Jordan',
 'Navos',
 'Murray Head',
 'The Jimmy Castor Bunch',
 'Amy Meredith',
 'Texas',
 'Morgan Evans',
 'Metro Boomin',
 '21 Savage',
 'Shab',
 'Martinez Twins',
 'Bootsy Collins',
 'Dick & Dee Dee',
 'Jebediah',
 'Mike Posner',
 'AC/DC',
 'Leah Haywood',
 'Cliff Richard',
 "Fiddler's Dram",
 'Faker',
 "Youssou N'Dour",
 'Neneh Cherry',
 'Nicole Kidman',
 'Bloodhound Gang',
 'DEVO',
 'The Irish Rovers',
 'Aston Merrygold ',
 'Ben Lee',
 'TOTO',
 'Machine Gun Kelly',
 'Johnny Ruffo',
 'Johnny Young & Kompany',
 'Leif Garrett',
 'A.B. Original',
 'Grey',
 'Eamon',
 'Ethan Sak',
 'Liz Becker',
 'Bad Company',
 'Kaiser Chiefs',
 'Andy Grammer',
 'Skeeter Davis',
 'Seal',
 'Thirsty Merc',
 'Noiseworks',
 'Nicky Youre',
 'dazy',
 'The Outfield',
 'SUPER-Hi',
 'NEEKA',
 'OMI',
 'Felix Jaehn',
 'Patsy Gallant',
 'Rivers Cuomo',
 'Angèle',
 'R. City',
 'Natalie Gauci',
 'The Wombats',
 'All Saints',
 'Passengers',
 'Luciano Pavarotti',
 'Ohio Express',
 'Take That',
 'Moodbay',
 'Grayson Hugh',
 'MN8',
 'Imanbek',
 'The Presidents Of The United States Of America',
 'Zephyr Alabama',
 'Abishi Taylor',
 'The Turtles',
 'Matt B',
 'The Royal Guardsmen',
 'Blur',
 'Baby Bash',
 'Frankie J',
 'Kandi',
 'Tammy Wynette',
 'Hootie & The Blowfish',
 'The Dudley Moore Trio',
 'David Cassidy',
 'Dragon',
 'Naughty By Nature',
 'José Feliciano',
 'Carla Thomas',
 'Jimmy Smith',
 'The Wanted',
 'Rick Astley',
 'Ernie K-Doe',
 'Jennifer Paige',
 'Liam Payne',
 'WSTRN',
 'Naughty Boy',
 'RØMANS',
 'Pete Townshend',
 'Good Charlotte',
 'Galantis',
 'Megan Thee Stallion',
 'Lucas & Steve',
 'Blackstreet',
 'Beastie Boys',
 'ICEHOUSE',
 'Nirvana',
 "Ol' 55",
 'Gordon Lightfoot',
 'Perry Como',
 'Green Jelly',
 "The Master's Apprentices",
 'Logic',
 'The Everly Brothers',
 'The Rebels',
 'MGMT',
 'Bob Marley & The Wailers',
 'Fifth Harmony',
 'Fetty Wap',
 'Steve Forbert',
 'Yazz',
 'Hank Snow',
 'iio',
 'Nadia Ali',
 'The McCoys',
 'Jump Jump Dance Dance',
 'Glen Campbell',
 'Jeanne Black',
 'Freddy Cannon',
 'The Supremes',
 'Badfinger',
 'Dimitri Vegas & Like Mike',
 'Dimitri Vegas',
 'James Bay',
 'Lifehouse',
 'Love\\',
 'Marco',
 'Iyaz',
 'Robert DeLong',
 'James Brown',
 'Eric Prydz',
 'Ugly Kid Joe',
 'Snakehips',
 'Wiley',
 'Sandrine',
 'Scissor Sisters',
 'Mario Millo',
 'The Manhattan Transfer',
 'The Verve Pipe',
 'Cardi B',
 'Blessid Union Of Souls',
 'David Kershenbaum',
 'Enigma',
 'David Essex',
 'Faith Evans',
 '112',
 'Crosby\\',
 'Stills\\',
 'Nash & Young',
 'Dario G',
 'Climax Blues Band',
 'Soft Cell',
 'BBE',
 'Bag Raiders',
 'Patti LaBelle',
 'Rufus Thomas',
 'Glass Animals',
 "Fat Larry's Band",
 'Lou Gramm',
 'Tee-Set',
 'Skrillex',
 'Poo Bear',
 'Kelis',
 'Alison Wonderland',
 'Sailor',
 'Charlie Rich',
 'Garnet Mimms',
 'The Enchanters',
 'Missy Higgins',
 '3OH!3',
 'The Doors',
 'Glenn Frey',
 'Chris de Burgh',
 'Amy Lee',
 'Del Shannon with Orchestra',
 'MIKA',
 'Stellar',
 'The Beautiful Girls',
 'The Youngbloods',
 'Diesel',
 'Phoenix',
 'Tracy Bonham',
 'Horst Jankowski',
 'Jack Joseph Puig',
 'Gabriella Cilmi',
 'Bradley Cooper',
 'The Corsairs',
 'The World',
 'Freedom Williams',
 'Mr. Big',
 'Oasis',
 'Lloyd',
 'André 3000',
 'The Kid LAROI',
 'The Impressions',
 'Ivy Adara',
 'Marshall Hain',
 'Pat Boone',
 'Yolanda Be Cool',
 'DCup',
 'East 17',
 'The Dandy Warhols',
 'SAINt JHN',
 'Desmond Dekker',
 'Paper Lace',
 'Jennifer Love Hewitt',
 'Marvin Priest',
 'Dido',
 'Fatman Scoop',
 'Marty Rhone',
 'Angel Azmeer',
 'Ben Folds',
 'Walter Murphy',
 'Allman Brothers Band',
 'Jax Jones',
 'Ina Wroldsen',
 'Illy',
 'Terry Stafford',
 'Bill Conti',
 'FRENSHIP',
 'Emily Warren',
 'The Corrs',
 'David Cole',
 'Amber',
 'Eiffel 65',
 'Nelly Furtado',
 'Sidney Samson',
 "Cut 'N' Move",
 'Dr. Alban',
 'Limahl',
 'Chiddy Bang',
 'Steve Earle',
 'Blue Öyster Cult',
 'PNAU',
 'Scouting For Girls',
 'The Archies',
 'Aleesha Rome',
 'Bratz',
 'Eric Burdon & the Animals',
 'Hurts',
 'OK Go',
 'Billy Field',
 'Ini Kamoze',
 'The Doobie Brothers',
 'Rob Thomas',
 'Hank Locklin',
 'Nicky Romero',
 'Bell Biv DeVoe',
 'Guy Mitchell',
 'Gossip',
 'Heather Small',
 'Debbie Harry',
 'Quiet Riot',
 'Hilltop Hoods',
 'Cobra Starship',
 'Leighton Meester',
 'John Lennon',
 'Ronnie Burns',
 'Reece Mastin',
 'Angus & Julia Stone',
 'R.E.M.',
 "Quad City DJ's",
 'The Cars',
 'Gnarls Barkley',
 'Röyksopp',
 'Bobbie Gentry',
 'Christine Anu',
 'Drapht',
 'Joe Walsh',
 'LeAnn Rimes',
 'James Chatburn',
 'ZHU',
 'SNAP!',
 'EMF',
 'The Power Station',
 'The Cat Empire',
 'Rachel Platten',
 'Majestic',
 'Boney M.',
 'Sleepy Tom',
 'Sananda Maitreya',
 'Brandy',
 'Sam & Dave',
 'Phil Collins',
 "Leonardo's Bride",
 'Martha Reeves & The Vandellas',
 'The Strangers',
 'Jack Harlow',
 'Dee Dee Sharp',
 'Everything But The Girl',
 'Zank',
 'STORME',
 'Bobby Bare',
 'Bachman-Turner Overdrive',
 'The Black Sorrows',
 'Eagles',
 'Moloko',
 'Kelsea Ballerini',
 'Midnight Juggernauts',
 'Frank Ifield',
 'Luis Fonsi',
 'Daddy Yankee',
 'Candy Dulfer',
 'Paul Simon',
 'Ritt Momney',
 'Sarah Connor',
 "Boys Don't Cry",
 'Bobby Rydell',
 'The Darkness',
 'Big Mountain',
 'Tom Lord-Alge',
 'The Lettermen',
 'Paul Norton',
 "Scott Bradlee's Postmodern Jukebox",
 'Cristina Gatti',
 'Steve Harley',
 'Steve Harley & Cockney Rebel',
 'Kids Of 88',
 'Normie Rowe',
 'REO Speedwagon',
 'Fleur East',
 'ROZES',
 'Michael Paynter',
 'The Searchers',
 'Finger Eleven',
 'James Hype',
 'Miggy Dela Rosa',
 "Israel Kamakawiwo'ole",
 'Chris Isaak',
 '24kGoldn',
 '10cc',
 'Eric Clapton',
 'Loudon Wainwright III',
 'Parachute',
 'Matt Corby',
 'John Waite',
 'Mr. Mister',
 'My Chemical Romance',
 'Vikki Carr',
 'Melanie Dyer',
 'ZZ Top',
 'Brenton Wood',
 'The Dave Clark Five',
 'Free',
 'Mr. President',
 'Sam Sparro',
 'Internet Money',
 'Gunna',
 'Don Toliver',
 'NAV',
 'Womack & Womack',
 'Cher Lloyd',
 'N-Trance',
 'Kenny Hayes',
 'Cassie Davis',
 'Paul Anka',
 'Odia Coates',
 'Steppenwolf',
 'Los Lobos',
 'Duck Sauce',
 'The Clash',
 'Gene Pitney',
 'alt-J',
 'Ruel',
 'M-Phazes',
 'Tina Arena',
 'Foxes',
 'Lennon & Maisy',
 'Benny Benassi',
 'Tove Lo',
 'Hippie Sabotage',
 'Bob Welch',
 'The Jacksons',
 'Small Faces',
 'Fairground Attraction',
 'Natalie Taylor',
 'The Rah Band',
 'Baauer',
 'Dakota',
 'Heintje',
 'Nicole Scherzinger',
 'New Politics',
 'JAY-Z',
 'Luke Steele',
 'Albert Hammond',
 'Aaron Neville',
 'HAIM',
 'Rose Royce',
 'Ashe',
 'Ofenbach',
 'Vampire Weekend',
 'Walter Brennan',
 'The Johnny Mann Singers',
 'Steve Winwood',
 'Clever',
 'Carly Simon',
 'Natalie Imbruglia',
 'Amy Pearson',
 'Men Without Hats',
 'Walter Meego',
 'The Brothers Johnson',
 'Bond',
 'New Boyz',
 'Lily Allen',
 'Jackie DeShannon',
 'Missing Persons',
 'King',
 'Kate DeAraugo',
 'Gyan',
 'Plan B',
 'S1mba',
 'DTG',
 'Alexandra Stan',
 'Deee-Lite',
 'The Heartland Collective',
 'Yello',
 'Laura Branigan',
 'Toto Coelo',
 'Genesis',
 'Meg Mac',
 'Pete Murray',
 'Helen Reddy',
 'Beats International',
 'The Swinging Blue Jeans',
 "Mousse T. Vs Hot 'n' Juicy",
 'Scandal',
 'Patty Smyth',
 'Dennis Waterman',
 'Jesse McCartney',
 'Sandy Posey',
 'The Four Preps',
 'The Serendipity Singers',
 'Diana King',
 'Ray Stevens',
 'The Chantays',
 'Travis Barker',
 'Morcheeba',
 'Katy B',
 'Ms. Dynamite',
 'Wizzard',
 'Wild Belle',
 'A Touch Of Class',
 'Pete Konemann',
 'Sister Sledge',
 'Tori Kelly',
 'Aaliyah',
 'The Blessed Madonna',
 'Lou Christie',
 'Sean Quinn',
 'Gus Cullen',
 'Yellowstone And Voice',
 'Ringo Starr',
 'Dawn',
 'Tony Orlando',
 'Dada Pop',
 'Newton Faulkner',
 'The Yardbirds',
 'Bruce Springsteen',
 'Sammi Constantine',
 'Voyager',
 'Spice Girls',
 'Diana Ross & The Supremes',
 'Frankie Valli & The Four Seasons',
 'Black Rob',
 'Mark Curry',
 'Meck',
 'The Lonely Island',
 'Marcia Hines',
 'Zoë Badwi',
 'Max-A-Million',
 'Lynyrd Skynyrd',
 'Foster The People',
 'Spiderbait',
 'Shocking Blue',
 'Adam Wade',
 'The Outhere Brothers',
 'Sabi',
 'KT Tunstall',
 'B2K',
 'Augie March',
 'Liam Lynch',
 'Justin Wellington',
 'Small Jam',
 'The Bachelors',
 'CHIC',
 'Dead Reynolds',
 'Rik Rok',
 'DJ Cassidy',
 'Robin Thicke',
 'Sweet',
 'Feargal Sharkey',
 'Ty Dolla $ign',
 'Gordon Taggart',
 'T-Pain',
 'Fugees',
 'Pras',
 'The Rubettes',
 'Jaden',
 'Sylvester',
 'The Fifth Estate',
 'Lauren Bennett',
 'GoonRock',
 'Man 2 Man',
 'Bananarama',
 'Daya',
 'The Partridge Family',
 'La Bouche',
 'Martha Davis',
 'Ozzy Osbourne',
 'Lennon Stella',
 'Marianne Faithfull',
 'The Calling',
 'Middle Of The Road',
 'Panjabi MC',
 'Phoebe Ryan',
 'Kodaline',
 'Rosa Linn',
 'Quindon Tarver',
 'Josh Abrahams',
 'Mike Oldfield',
 'American Authors',
 'Sam Bailey',
 'Imany',
 'Filatov',
 'Karas',
 'Tom Grennan',
 '2 Unlimited',
 'Dr. Dre',
 'Queen Pen',
 'Megan Davies',
 'Owl City',
 'Haddaway',
 'Ace of Base',
 'Shep And The Limelites',
 'Joe Tex',
 'Skylar Grey',
 'Toploader',
 'Tony Barber',
 'The Chiffons',
 'Simple Minds',
 'Rauw Alejandro',
 'Pharrell Williams',
 'Uncle Charlie Wilson',
 'Stray Cats',
 'Pat Benatar',
 'Savage',
 'Lesley Gore',
 'Nikki Webster',
 'Peking Duk',
 'Cover Drive',
 'Bruce Ruffin',
 'L.A. Style',
 'Dee C. Lee',
 'Tom Walker',
 'Bad Meets Evil',
 'Roger',
 'Birtles & Goble',
 'Echosmith',
 'Montaigne',
 'Tom Thum',
 'Superstar',
 'Freshlyground',
 'Johnny Diesel & The Injectors',
 'The Exciters',
 'Fox',
 'Milky Chance',
 'Passion Pit',
 'Chingy',
 'Jason Weaver',
 'Dan + Shay',
 'Bobby Day',
 'Ollie Gabriel',
 'The Box Tops',
 'What So Not',
 'LPX',
 'Quarterflash',
 'Oliver Tree',
 'Robin Schulz',
 'The Drifters',
 'Who Is Fancy',
 'Rock Hits',
 'Poison',
 'Bread',
 "Johnny O'Keefe",
 'The Saints',
 'Jessie Ware',
 'Dave Dobbyn',
 'Herbs',
 'Pseudo Echo',
 'The Vapors',
 'Ernest Gold',
 'Charles Eugene Patrick Boone',
 'Ferrante & Teicher',
 'Klangkarussell',
 'Otto Knows',
 'Johnny Mathis',
 'Whitesnake',
 'Vanilla Ice',
 'Lauren Daigle',
 'Fats Domino',
 'Shona Laing',
 "DMA'S",
 'Living Colour',
 'Bow Wow',
 'Loud Luxury',
 'Big Shaq',
 'Lauren Spencer Smith',
 'The Dawn',
 'Tony Orlando & Dawn',
 'Major Lance',
 'Architecture In Helsinki',
 "Manfred Mann's Earth Band",
 'Adrian Eagle',
 'The Mavericks',
 'Sinitta',
 'Raydio',
 'Nicki French',
 'Dion',
 'Garbage',
 'Tkay Maidza',
 'J-Kwon',
 'X Ambassadors',
 'Marian Hill',
 'Freda Payne',
 'Fakebitcheshero',
 'Debby Boone',
 'The Church',
 'Leapy Lee',
 'The Rip Chords',
 'The Band',
 'The Shangri-Las',
 'Harold Faltermeyer',
 'James Taylor',
 'Def Leppard',
 'Bardot',
 'Utah Saints',
 'MEDUZA',
 'Dermot Kennedy',
 'Silience',
 'Dino Jag',
 'Damien Reilly',
 'Ray Columbus and the Invaders',
 'The Three Degrees',
 'Barry McGuire',
 'Quavo',
 "The Lovin' Spoonful",
 'Julian Lennon',
 'Alex Clare',
 'Animotion',
 'John Stewart',
 'Drax Project',
 'Ultravox',
 'ELVIRA',
 'Sue Thompson',
 'Mumford & Sons',
 'Matthew Wilder',
 'Static Revenger',
 'Bad English',
 'Marie Osmond',
 'Status Quo',
 'Ben E. King',
 'Shirley Bassey',
 'Linda George',
 'All-4-One',
 'O.C. Smith',
 'Warren G',
 'Nate Dogg',
 'The Style Council',
 'Eydie Gormé',
 'Chynna Phillips',
 'Mr G',
 'Chris Montez',
 'The Ray Conniff Singers',
 'The Superjesus',
 'The Temper Trap',
 'S Club',
 'The Ting Tings',
 'MC Miker & DJ Sven',
 'Freya Ridings',
 'The Little Dippers',
 'Twisted Sister',
 'Jon & Vangelis',
 'Julie Rogers',
 'Hans Poulsen',
 'James Blunt',
 'Darryl Cotton',
 "Des'ree",
 'Night',
 'The Fendermen',
 'Gabrielle Aplin',
 'Blue Mink',
 'Peabo Bryson',
 'AJ Mitchell',
 'Chuck Berry',
 'Fat Joe',
 'John Butler Trio',
 'Barry Manilow',
 'The Orlons',
 'The Jive Five',
 'The Romantics',
 'Mondo Rock',
 'Jan Bradley',
 'Puddle Of Mudd',
 'RANI',
 'Austen Tayshus',
 'Lonestar',
 'Ocean Alley',
 'DNA',
 'Suzanne Vega',
 'Donna Lewis',
 'Chantoozies',
 'The Shirelles',
 'Ed Sheeran & Justin Bieber',
 'Maren Morris',
 'Gorgon City',
 'Jennifer Hudson',
 'Derek & The Dominos',
 'P.O.D.',
 'Gary Puckett & The Union Gap',
 'Benedict',
 'deadmau5',
 'Kaskade',
 'Janieck Devy',
 'Nelson',
 'Carly Rae Jepsen',
 'L.V.',
 'The Guess Who',
 'Harry Secombe',
 'Myke Towers',
 'Tainy',
 'Rooftop Heroes',
 'Joe Cocker',
 'Jamie Scott',
 'Romy Dya',
 'Nevada',
 'Mark Morrison',
 'Sean Kingston',
 'The Radiators',
 'The Communards',
 'Operator Please',
 'Cream',
 'Rizzle Kicks',
 'Childish Gambino',
 'The Cascades',
 'Kris Kross Amsterdam',
 'UB40',
 'Baker Boy',
 'Margaret Urlich',
 'Minnie Riperton',
 'Barry Blue',
 'The Tremeloes',
 'Lighter Shade Of Brown',
 'Grand Funk Railroad',
 '38 Special',
 'Moby',
 'Jackson Jackson',
 'Gia Farrell',
 'Don Omar',
 'Lucenzo',
 'Scatman John',
 'Endor',
 'Nathan Evans',
 '220 KID',
 'Stevie B',
 'Skip & Flip',
 'Muse',
 'Sunset City',
 'Mary Hopkin',
 'Idris Elba',
 'Anderson .Paak',
 'Lenka',
 'Royal Philharmonic Orchestra conducted by Louis Clark',
 'Rick Springfield',
 'The Stone Roses',
 'Kelly Marie',
 'Herb Ohta\\',
 'Sr.',
 'Commodores',
 'Anitta',
 'Robbie Nevil',
 'The Jordanaires',
 'Concrete Blonde',
 'Carrie Underwood',
 'Nils Landgren Funk Unit',
 'Maisie Peters',
 'T-Shirt',
 'SAM WHITE',
 'Roger Voudouris',
 'Yes',
 'BTS',
 'Desiigner',
 'Jay R',
 'Sarah Jane Morris',
 'Alex Party',
 'Carpenters',
 'Yusuf',
 'Cut Copy',
 'Peppermint Heaven',
 'The Marvelettes',
 'The Weather Girls',
 'Asta',
 'Allday',
 'The Manhattans',
 'Rupert Holmes',
 'Audio Bullys',
 'The Lumineers',
 'Gladys Knight',
 'The Pips',
 'Adrian Gurvitz',
 'Monifah',
 'Heinz',
 'Brooks Jefferson',
 'Showtek',
 'VASSY',
 'Philip Bailey',
 'The Wallflowers',
 'MSTRKRFT',
 'John Legend',
 'Melissa Tkautz',
 'Russell Morris',
 'Lieutenant Pigeon',
 'Sam Perry',
 'Billy Thorpe',
 'Village People',
 'WALK THE MOON',
 'Sam Brown',
 'Pete Brown',
 'Tuka',
 'Lo-tel',
 'Tammin Sursok',
 'Ray Hedges',
 'Sash!',
 'George Benson',
 'Eric Weissberg',
 'Steve Mandell',
 'Brownsville Station',
 'Armand Van Helden',
 'Boy George',
 "Sergio Mendes & Brasil '66",
 'Talking Heads',
 'Lawrence Welk',
 'Larry Verne',
 'Nine Days',
 'Jann Arden',
 'Marcus Marr',
 'Nick Murphy',
 'Ray Peterson',
 'Mary MacGregor',
 'Sore',
 'Darling Brando',
 'The Game',
 'Itch',
 'Megan Joy',
 'Steely Dan',
 'Tommy Sparks',
 'Twiztid',
 'Ice Nine Kills',
 'Chart Collective',
 'Third Eye Blind',
 'Van Halen',
 'Blue Swede',
 'Björn Skifs',
 'Gary Glitter',
 'The Spencer Davis Group',
 'William Shakespeare',
 'Little Red',
 'White Plains',
 'Alice Deejay',
 'Tim McGraw',
 'Sam Fischer',
 'Christie Allen',
 'Robert John',
 'Christopher Cross',
 'Freddy Fender',
 'twocolors',
 'Crystal Gayle',
 'Zac Efron',
 'Zendaya',
 'Paulini',
 'Passenger',
 'Wesley Dean',
 'Coi Leray',
 'Johnny Maestro',
 'Chris Norman',
 'ALMA',
 'Roger Miller',
 'Lou Reed',
 'Jørgen Ingmann',
 'Jessie James Decker',
 'Bobby Vinton',
 'The Chicks',
 'The Art Of Noise',
 'Sonique',
 'Jon Bellion',
 'Los Del Mar',
 'Wil Veloz',
 'Eva Simons',
 'Chris Rea',
 'Norman Greenbaum',
 'Alex Orbison',
 'Chuck Turner',
 'Joshua Kadison',
 'Mick Jagger',
 'J Rice',
 'Pretenders',
 'Matt Terry',
 'Abz Winter',
 'The Village Stompers',
 'Seals and Crofts',
 'The HamilTones',
 'Wale',
 'Julee Cruise',
 'Lisa Mitchell',
 'Debelah Morgan',
 'Saigon Kick',
 'Hurricane Smith',
 'Band Aid',
 'Marilyn Manson',
 'The Nolans',
 'Kyla',
 'Kim Petras',
 'Count Five',
 'Fine Young Cannibals',
 'Vengaboys',
 'The New Seekers',
 'The Greg Kihn Band',
 'Hoobastank',
 'Love Ghost',
 'Club Nouveau',
 'Deborah Conway',
 'Clarence Clemons',
 'Jackson Browne',
 'Ashton\\',
 'Gardner & Dyke',
 'The Miracles',
 'The Proclaimers',
 'The Troggs',
 'Neil Sedaka',
 'Wet Wet Wet',
 'Wheatus',
 'Myglö',
 'The Cataracs',
 'DEV',
 'Becky Hill',
 'Goodboys',
 'Supertramp',
 'Tony! Toni! Toné!',
 'Marc Cohn',
 'Baha Men',
 'Harold Melvin & The Blue Notes',
 'Teddy Pendergrass',
 'DJ Jazzy Jeff & The Fresh Prince',
 'Mungo Jerry',
 'K.W.S.',
 'Survivor',
 'Brian McKnight',
 'Taylor Dayne',
 'Ray J',
 'Sly & The Family Stone',
 'Pia Mia',
 'Tyga',
 'Gloria Gaynor',
 'Bobby Sherman',
 'Joel Corry',
 'The Charlie Daniels Band',
 'De La Soul',
 'Hugo Montenegro & His Orchestra',
 'Hugo Montenegro',
 'The Tamperer',
 'Maya',
 'Mr Hudson',
 'The Collective',
 'Color Me Badd',
 'Captain & Tennille',
 'Jadakiss',
 'Styles P',
 'The Business Intl',
 'Will Sparks',
 'Skid Row',
 'Roy Head And The Traits',
 'Eagle-Eye Cherry',
 'Gerry & The Pacemakers',
 'Back In Black',
 'BLACKPINK',
 'Peter Sarstedt',
 'U.S.U.R.A.',
 'Keane',
 'Cash Backman',
 'Hermitude',
 'Mataya',
 'TAPZ GALLANTINO',
 'Styx',
 'Natalie La Rose',
 'Jeremih',
 'Whigfield',
 'Hamilton\\',
 'Joe Frank & Reynolds',
 'Little Boots',
 'Nicole Millar',
 'LunchMoney Lewis',
 'Chloe Angelides',
 'NERO',
 'Bob Seger',
 'Roger Sanchez',
 'Ladyhawke',
 'Player',
 'The Casuals',
 'Hozier',
 'Wendy Matthews',
 'Jean Knight',
 'Toni Childs',
 'Charles & Eddie',
 'Dave Edmunds',
 'The Commitments',
 'Andrew Strong',
 'Chris Kenner',
 'The Black Crowes',
 'G Flip',
 'Randy VanWarmer',
 'Kenny Rogers',
 'Dolly Parton',
 "Rag'n'Bone Man",
 'Golden Earring',
 'Waze & Odyssey',
 'Tommy Theo',
 'Casey Abrams',
 'Gina G',
 'Amerie',
 'Charlie Wilson',
 'Groove Coverage',
 'Mase',
 'Georgia Fair',
 'Vitamin C',
 'DJ Khaled',
 'Chance the Rapper',
 'Toni Basil',
 'Amii Stewart',
 'David Foster',
 'Swanee',
 'The Trashmen',
 'Troy Shondell',
 '1910 Fruitgum Company',
 'Con-Psy',
 '4 Non Blondes',
 'Russell Dickerson',
 'City Boy',
 'Lonnie Donegan',
 'Robert Miles',
 'Janis Ian',
 'Kim Hart',
 'Don & Juan',
 'Looking Glass',
 'Europe',
 'Machinations',
 'Deniece Williams',
 'J.J. Cale',
 'Rui Da Silva feat. Cassandra',
 'Mary Wells',
 'Get Wet',
 'Crazy Frog',
 'Tinie Tempah',
 'Grafton Primary',
 'Nelle Hooper',
 'Leon Russell',
 'Ashnikko',
 'Sheila E.',
 'Gramophonedzie',
 'POOLCLVB',
 'DOOLIE',
 'Jan & Dean',
 'Ricardo Da Force',
 'Keith Sweat',
 'Samantha Mumba',
 'Lil Pump',
 'Tamia',
 'Smokey Robinson',
 'NOTD',
 'Bea Miller',
 'Marcella Detroit',
 'Alesha Dixon',
 'Ross Ryan',
 'Girl Thing',
 'Marvin Hamlisch',
 'Nas',
 'NF',
 'Johnny Wakelin',
 'Bobby Vee',
 'Cassette Kids',
 '5000 Volts',
 "Booker T. & the M.G.'s",
 'Anastacia',
 'Rozalla',
 'Stephanie McIntosh',
 'Claude King',
 'Tarrus Riley',
 'Pilot',
 'Trevor Daniel',
 'Two Man Band\\',
 'The',
 'The Members',
 'Dru Hill',
 'Jimmy Osmond',
 'Chet Faker',
 'Nathan Sykes',
 'Gigamesh',
 'Models',
 'Indigo Girls',
 'Amity Dry',
 'Honeyz',
 'Josef Salvat',
 'Mario Winans',
 'Wafia',
 'Natalie Cole',
 'AWOLNATION',
 'Connie Stevens',
 'Joe Nichols',
 'The Seekers',
 'gnash',
 "Olivia O'Brien",
 'Twenty One Pilots',
 'Professor Green',
 "Des O'Connor",
 'Everclear',
 'Lindsey Buckingham',
 'Anita Ward',
 'Kiiara',
 'Jack Scott',
 'JoJo',
 'Adina Howard',
 'Kate Ceberano',
 'Tim & Jean',
 'Dionne Warwick',
 'Lewis Capaldi',
 'Kehlani',
 'Louisa Johnson',
 'Dirty South',
 'Rudy',
 'Santa Esmeralda',
 'Leroy Gomez',
 'Robin Gibb',
 'Meg Washington',
 'Redbone',
 'Ella Mai',
 'Regina Belle',
 'Disney',
 'Grandmaster Flash & The Furious Five',
 'Silk Sonic',
 'Ben Folds Five',
 'SHY FX',
 'Morgan Wallen',
 'Don Fardon',
 'Amanda Perez',
 'MKTO',
 'R.B. Greaves',
 'Alison MacCallum',
 'Technotronic',
 'Johnny Preston',
 'Bingoboys',
 'Jefferson Airplane',
 'The Band Perry',
 'Johnny Farnham',
 'Night Ranger',
 'Doop',
 'Howard Jones',
 'Redman',
 'KIDDO',
 'The Bobby Fuller Four',
 'Ilsey',
 'Blancmange',
 'Elle King',
 'Placebo',
 'Houston',
 'I-20',
 'Dean Ray',
 'Ocean',
 'Tinashe',
 'Ghost Town DJs',
 'Kevin Johnson',
 'Joan Osborne',
 'Brownstone',
 'Stacie Orrico',
 'Focus',
 'Duane Harden',
 'Josefine',
 'DJ Boat',
 'Dickie Lee',
 'The Korgis',
 'You Am I',
 'Tal Bachman',
 'Billy Preston',
 'B.B. King',
 'Paces',
 'Jess Kent',
 'Jamiroquai',
 'The Ritchie Family',
 'Marky Mark And The Funky Bunch',
 'Loleatta Holloway',
 'Bus Stop',
 'Carl Douglas',
 'Deadstar',
 'Johnny Horton',
 'Jo Jo Zep and The Falcons',
 'a-ha',
 'Ida Corr',
 'Planet Funk',
 'Harry Nilsson',
 'Dan Caplen',
 'Henry Mancini',
 'Avalanche City',
 'Go West',
 'Otis Redding',
 'Bette Midler',
 'Corona',
 'Hush',
 'Ernie Maresca',
 'Jocelyn Enriquez',
 'Hinder',
 'Aleem',
 'Sigrid',
 'The Foundations',
 'Paula Abdul',
 'Marc Anthony',
 'Anne & Johnny Hawker',
 'Big Brovaz',
 'Pure Prairie League',
 'Abs Breen',
 'JID',
 'Arcane',
 'League of Legends',
 'Stevie Wright',
 'Jesus Jones',
 'Art vs Science',
 'Graham Bonnet',
 'Jack River',
 'ROSÉ',
 'Peter Blakeley',
 'Sister Janet Mead',
 'Promises',
 'DJ BoBo',
 'Melodie MC',
 'Dan Hill',
 'The Groop',
 'Benny Hill',
 'The Highwaymen',
 'Kelly Rose',
 'Ketty Lester',
 'The Spinners',
 'O-Zone',
 'Switchfoot',
 'Lloyd Price',
 'Rob E.G.',
 'Jennifer Rush',
 'Nick Waterhouse',
 'Loretta Lynn',
 'The Smashing Pumpkins',
 'Fastball',
 'Blind Melon',
 'Stormzy',
 'Burna Boy',
 'The Buggles',
 'Wrabel',
 'Twenty 4 Seven',
 'A$AP Rocky',
 'Frente!',
 'Dave & Ansell Collins',
 'The Cardigans',
 'Wolfgang Gartner',
 'Clarence Carter',
 'The Triffids',
 'Young Thug',
 'The Party Boys',
 'Sophie Monk',
 'Alicia Bridges',
 'Gino Vannelli',
 'Time Bandits',
 'A.R. Rahman',
 'Don McLean',
 'Paul Young',
 'Allure',
 'Luciana',
 'The Naked And Famous',
 'Rico Nasty',
 'Modjo',
 'Shannon',
 'Mike Taylor',
 'Em Beihold',
 'Diddy - Dirty Money',
 'Giveon',
 'The Hooters',
 'The Lemon Pipers',
 'Bob Kuban & The In-Men',
 'John Hiatt',
 'StaySolidRocky',
 'Cary Brothers',
 'Shift K3Y',
 'Joan Armatrading',
 'Cory Rooney',
 'Poke and Tone',
 'Thunderclap Newman',
 'Frankie Goes To Hollywood',
 'Dean Martin',
 'Alexia',
 'Jeff St John',
 'The ID',
 'Chicane',
 'Jaki Graham',
 'Jim Steinman',
 'Sophie Ellis-Bextor',
 'Jamelia',
 'Little Cesar & The Romans',
 'Gene Chandler',
 'Kosheen',
 'Nu Shooz',
 'Slip-On Stereo',
 'Prince Mydas',
 'Dawin',
 'Curtis Lee',
 'Sandro Cavazza',
 'Rockmelons',
 'Johnny & The Hurricanes',
 'Johnny Paris',
 'Charlene',
 'Gary Shearston',
 'City High',
 'The Click Five',
 '28 Days',
 'Brainbug',
 'Ella Fitzgerald',
 'Ray Brown And The Whispers',
 'Van Morrison',
 'Etta James',
 'Gerry Monroe',
 'Malcolm McLaren',
 'James Darren',
 'Mura Masa',
 'Friendly Fires',
 'Lazyboy',
 'Don Williams',
 'Joe South',
 'PON CHO',
 'Paige IV',
 'Two Door Cinema Club',
 'LMC',
 'Wanz',
 'Brian Hyland',
 'LF SYSTEM',
 'Asaf Avidan',
 'The Mojos',
 'Wankelmut',
 'Liam Gallagher',
 'Alannah Myles',
 'The Immigrant',
 'Danny Ross',
 'Cassie',
 'Little Sea',
 'Queens of the Stone Age',
 'Pat Wilson',
 'Ray Dalton',
 'Haysi Fantayzee',
 'Gary Numan',
 'The Bellamy Brothers',
 'Fred again..',
 'Kelly Price',
 'The Kooks',
 'Felly',
 'Eddie Cochran',
 "Alan O'Day",
 'Topic',
 'A7S',
 'Lil Baby',
 'Kenny Ball',
 'WickedStranger',
 '3T',
 'Koo De Tah',
 'Young MC',
 'Mikky Ekko',
 'Dinah Washington',
 'Smokie',
 'We Five',
 'Alex Gaudino',
 'Crystal Waters',
 'Shakaya',
 'Kim Weston',
 'William Orbit',
 'YUNGBLUD',
 'Jessie Reyez',
 'Big Yavo',
 'The 12th Man',
 'Max Merritt',
 'The Meteors',
 'Christina Amphlett',
 'The Asteroids Galaxy Tour',
 'Curtis Mayfield',
 'Hugh Jackman',
 'Keala Settle',
 'The Greatest Showman Ensemble',
 'N.O.R.E.',
 'Urban Cookie Collective',
 'Bobby Bloom',
 'Al Green',
 'Disturbed',
 'Area-7',
 'Alice Merton',
 'The Cherokees',
 'MARINA',
 'Casey Donovan',
 'Mi-Sex',
 'Dirty Vegas',
 'Slinkee Minx',
 'Duke Dumont',
 'Ebenezer',
 'Graham Nash',
 'Pryma',
 'Sam Hunt',
 'JP Cooper',
 'Stealers Wheel',
 'Mac Miller',
 'Elliott Yamin',
 'Hunter Hayes',
 'Huey Lewis & The News',
 'Del The Funky Homosapien',
 'Zager & Evans',
 'Toni Pearen',
 'Lights',
 'John David',
 'Frankie Miller',
 'Delaney & Bonnie',
 'The Go-Betweens',
 'Silk',
 'Benjamin Joseph',
 'Newton',
 'Londonbeat',
 'Jazmine Sullivan',
 'Joe Publick',
 "Livin' Joy",
 'Paul Morrell',
 'Morris Albert',
 'ATB',
 'Bachelor Girl',
 '2 In A Room',
 'The Isley Brothers with Orchestra',
 'Jim Capaldi',
 'The Prodigy',
 'The Cruel Sea',
 'Zac Brown Band',
 'Ratcat',
 '98º',
 'Sisqo',
 'Johnny Logan',
 'Dómisol Sisters',
 'Tim Deluxe',
 'Sam Obernik',
 'Bad Bunny',
 'Jhayco',
 'Paul Evans',
 '3 The Hard Way',
 'Sam Martin',
 'Anne Murray',
 'Alien Ant Farm',
 'The xx',
 'Patrick Swayze',
 'Wendy Fraser',
 'The Move',
 'Lobo',
 'Iggy Pop',
 'Juicy J',
 'Bertie Higgins',
 'Luke Christopher',
 'CoCo Lee',
 'Crush',
 'MAX',
 'Black Box',
 'Miike Snow',
 'Kyu Sakamoto',
 'Bipolar Sunshine',
 'Juice WRLD',
 "The La De Da's",
 'Daddy Dewdrop',
 'Baccara',
 'Jim Diamond',
 'Yoko Ono',
 'Soulja Boy',
 'The Hombres',
 'Dion & The Belmonts',
 'Steve Perry',
 'Blue Boy',
 'Stu Stone',
 'Vicki Lawrence',
 'Flume',
 "Lazaro's Dog",
 'Bert Kaempfert',
 'Amiel',
 'Jon Bon Jovi',
 'Nico Santos',
 'Clyde McPhatter',
 'Roy Orbison & Teen Kings',
 'Las Ketchup',
 'Ray Charles',
 'Lilly Wood and The Prick',
 'Sixpence None The Richer',
 'Dean Geyer',
 'Hedgehoppers Anonymous',
 'Et Cetera',
 'Kincade',
 'Bill Haley & His Comets',
 'Nile Rodgers',
 'Foster & Allen',
 'Juice Newton',
 'Dexys Midnight Runners',
 'Lil Yachty',
 'Matthew Koma',
 'Bobby Goldsboro',
 'Ian Carey',
 'BROODS',
 'Madison Avenue',
 'Blackfeather',
 'Sarah Brightman',
 'Mike Mago',
 'Dynamic Hepnotics',
 'D12',
 'George',
 'Starland Vocal Band',
 'Chrom3',
 'Lynn Anderson',
 'Rachel Mintz',
 'Dsblade',
 'Tubeway Army',
 'Willow Sage Hart',
 'Elley Duhé',
 'HOSH',
 '1979',
 'Jalja',
 'The Twilights',
 'Kaleb Jones',
 'Paul Mac',
 'Chris Farlowe',
 'Lipps Inc.',
 'The Bootleg Family Band',
 'Paul Dempsey',
 'Ken Dodd',
 'Claes Janson',
 'Joel Daydé',
 'Riton',
 'Nightcrawlers',
 'Mufasa & Hypeman',
 'Dopamine',
 'Delerium',
 'Sarah McLachlan',
 'Artists United Against Apartheid',
 'Kane Brown',
 'The Hollywood Argyles',
 'Avery Storm',
 'Jagged Edge',
 'Emerson\\',
 'Lake & Palmer',
 'Khia',
 'DJ Frank E',
 'CeCe Peniston',
 'Gloriana',
 'DJ Sammy',
 'Yanou',
 'Do',
 'Jud Strunk',
 'Don Gibson',
 'Surf Mesa',
 'Emilee',
 'The Brothers Four',
 'Napoleon XIV',
 'Eric Benét',
 'Kevin "K.D." Davis',
 'Joe Dowell',
 'DBX',
 'ILLENIUM',
 'Hight',
 'Alex Aiono',
 'Steps',
 'Nicholas McDonald',
 'Future',
 'Sammi Smith',
 'Loverboy',
 'NEWEM',
 'Baby Alpaca',
 'Scott Fitzgerald',
 'Yvonne Keeley',
 'Berri',
 'Icona Pop',
 'Brooklyn Dreams',
 'Samantha Fox',
 'Marty Guilfoyle',
 'John Gibbons',
 'Sir Mix-A-Lot',
 'Lighthouse Family',
 'Dixie Belles',
 'Cornbread & Jerry',
 'Los Indios Tabajaras',
 'Richard Vission & Static Revenger Starring Luciana',
 'Madison Beer',
 'Luke Combs',
 'LSD',
 'Kokomo',
 'The Byrds',
 'Vydamo',
 'Ike & Tina Turner',
 'The Waifs',
 'Ral Donner',
 'Kurupt',
 'Anita McCloud',
 'Natina Reed',
 'Keri Hilson',
 'D.O.E.',
 'Tame Impala',
 'Richard Clapton',
 'CHVRCHES',
 'Joe Jonas',
 'Judah Kelly',
 'Apollo 100',
 'Bob Sinclar',
 'Jimmy Dean',
 'Lukas Graham',
 'Gary Lewis & The Playboys',
 'AURORA',
 'Wes Nelson',
 'Girlfriend',
 'Dave Dee\\',
 'Dozy\\',
 'Beaky\\',
 'Mick & Tich',
 'Tommy James & The Shondells',
 'Edward Bear',
 'The Movement',
 'Rednex',
 "Albie Donnelly's Supercharge",
 'Michael Nesmith',
 'The First National Band',
 'Billy Joe & The Checkmates',
 'Joe Jackson',
 'Shinedown',
 'Jewel',
 'Transvision Vamp',
 'Procol Harum',
 'Visage',
 'Mark "Exit" Goodchild',
 'Stars On 54',
 'Bill Anderson',
 'Portugal. The Man',
 'Griff',
 'Sara Bareilles',
 'Barry Mann',
 'JXL',
 'Darren Hayes',
 'Slash',
 'Patsy Cline',
 'RUN',
 'Lamarquis Jefferson',
 'The Ronettes',
 'Stephen Sanchez',
 'Conway Twitty',
 'ABC',
 'The Supermen Lovers',
 'Mani Hoffman',
 'AFI',
 'QED',
 'Laurent Wery',
 'Swift K.I.D.',
 'Dev',
 'Jack Garratt',
 'Matt Flinders',
 'The Babys',
 'Edwin McCain',
 'Majid Jordan',
 'Joe Dolce',
 'Kimberly Anne',
 'Rascal Flatts',
 'Dominic Fike',
 'Boris Gardiner',
 'Rudy Thomas',
 'Steven Stanley',
 'Willie Lindo',
 'Dead By Sunrise',
 'Kym Mazelle',
 'The Grid',
 "Eric 'ET' Thorngren",
 'Gizzle',
 'Joel Adams',
 'Absolutely Fabulous',
 'Gabry Ponte',
 'Rick Price',
 'Ultimate Kaos',
 'Björk',
 'SHAED',
 'A-Type Player',
 'Sonny & Cher',
 'The Dovells',
 'Jonathan Groff',
 'Brian May & The ABC Showband',
 'Strawbs',
 'Chas & Dave',
 'Thirty Seconds To Mars',
 'Alle Farben',
 'Graham Candy',
 'Kevin Lyttle',
 'Thin Lizzy',
 'Meredith Brooks',
 'Judie Tzuke',
 'Benny Mardones',
 'Wolfmother',
 'Yo La Tengo',
 'Doctor & The Medics',
 'Bill & Boyd',
 'Random',
 'Barbara Ray',
 'Ellie Drennan',
 'Boy & Bear',
 'Bec Cartwright',
 'Guru Josh',
 'The Bucketheads',
 'Elkie Brooks',
 'Howie Day',
 'Gibson Brothers',
 'Four Tops',
 'CeeLo Green',
 'Hampton The Hampster',
 'Arctic Monkeys',
 'Throttle',
 'Blue',
 'Jimmy Clanton',
 'Vanilla Fudge',
 'Bobby "Boris" Pickett',
 'The Crypt-Kickers',
 'kai',
 'Reg Lindsay',
 'Solitaire',
 'Stardust',
 'Disciples',
 'Europa',
 'Divine',
 'Secondhand Serenade',
 'Elen Levon',
 'Israel Cruz',
 'New Radicals',
 'Small Mercies',
 'Klingande',
 'Nik Kershaw',
 'The Ventures',
 'World Party',
 'Anthony Thistlethwaite',
 'Georgie Fame',
 'Michelle Branch',
 'Sum 41',
 'Young Tapz',
 'Shawn Mullins',
 'Dan Black',
 'Mark Lindsay',
 'MNEK',
 'Marty Robbins',
 'The Ferrets',
 'Loggins & Messina',
 'BlocBoy JB',
 'Lady Saw',
 'Avant',
 'The Dingoes',
 'Lee Kernaghan',
 'José Carreras',
 'Ultra',
 'Steve Robson And Andy Bradfield',
 'Tesher',
 'Wilson Phillips',
 'Becky G',
 'Linda Scott',
 'Milli Vanilli',
 'Technohead',
 'Warren Zevon',
 'Cal Smith',
 'Ginuwine',
 'Kungs',
 "Cookin' On 3 Burners",
 'Billy Squier',
 "K's Choice",
 'A Great Big World',
 'PARTYNEXTDOOR',
 'Rebecca Levy',
 'Samantha Sang',
 'The Allniters',
 'Talent',
 'Deep Forest',
 'George Tobin',
 'Bill Smith',
 'Shelley Fabares',
 'Pop Smoke',
 'Isaac Hayes',
 'Tom Clay',
 'Nick Cave & The Bad Seeds',
 'Latto',
 'Fitz and The Tantrums',
 'Dale & Grace',
 'New World',
 'John Fred and His Playboy Band',
 'Bobby Anthony',
 'Yeasayer',
 'Alcazar',
 'Bob Carlisle',
 'Goanna',
 'Ruby And The Romantics',
 'Tag Team',
 'Mel & Kim',
 'Paul Anka et son orchestre',
 'Crispian St. Peters',
 'Inez Foxx',
 "Alisha's Attic",
 'Bernard Fanning',
 'Charlie Sloth',
 'Juai',
 'Lovey James',
 'Daniel Seavey',
 'Mylo',
 'Purple Disco Machine',
 'Sophie and the Giants',
 'Damien Rice',
 'Loreen',
 'James',
 'Steve Lawrence',
 'In-Grid',
 'Johnny Nash',
 'George Maple',
 'Naked Eyes',
 'Joel Fletcher',
 'Louie Austen',
 'Tyler Stone',
 'Climie Fisher',
 'Hocus Pocus',
 'Wizkid',
 "S'Express",
 'John Kongos',
 'Robinson',
 'Arizona Zervas',
 'Jimmy Cliff',
 'Glenn Shorrock',
 'The Cockroaches',
 'Bill Withers',
 'Silver Convention',
 'The Quick',
 'Francesco Yates',
 'Scratch Massive',
 'CHLOE (Thévenin)',
 'DOELD',
 'Uriah Heep',
 'KALEO',
 'Tenacious D',
 'Hi Tek 3',
 'Ya Kid K',
 'Kita Alexander',
 'The Rooftop Singers',
 'The Red Jumpsuit Apparatus',
 'Axwell /\\ Ingrosso',
 'Axwell',
 'Sebastian Ingrosso',
 'Joey Scarbury',
 '3LW',
 'Snow',
 'Mason Williams',
 'Daneka Nation',
 'Sparks',
 'Jim Croce',
 'DVBBS',
 'Borgeous',
 'DaChri',
 'Soundgarden',
 'Glenn Medeiros',
 'Spiller',
 'Cody Wise',
 'Dave Berry',
 'Kayls',
 'Nick Lowe',
 'Sunnyboys',
 'Portrait',
 'Zoot',
 '6LACK',
 'Hungry Kids of Hungary',
 'Midnight Star',
 'Starskee',
 'The Getaway Plan',
 'D. Pritzker',
 'Sonia Dada',
 'The Honeydrippers',
 'Maria Muldaur',
 'Doris Troy',
 'Johnny Chester',
 'Jive Bunny and the Mastermixers',
 'Fools Garden',
 'Sir Douglas Quintet',
 '99 Souls',
 'Tegan and Sara',
 'Bene',
 'Warrant',
 'Sunny & The Sunglows',
 'The Overlanders',
 'Kardinal Offishall',
 'Michael Gray',
 'Elderbrook',
 'Verdine White',
 'Boz Scaggs',
 'Alex Edmonds',
 'A Boogie Wit da Hoodie',
 'Basement Jaxx',
 'King Harvest',
 'Jimmy Jones',
 'Jeremy Zucker',
 'Penny McLean',
 'Karnivool',
 'The Animals',
 'King Curtis',
 'Klaxons',
 'The Echoes',
 'The Hoosiers',
 'Kim Carnes',
 'Sage The Gemini',
 'Lookas',
 'Sgt Slick',
 'NAATIONS',
 'Bingo Players',
 'Duncan Laurence',
 'Chain',
 'The Damned',
 'salem ilese',
 'Ph.D.',
 'Riff',
 'Deep Blue Something',
 'Luther Vandross',
 'Jess & Matt',
 'Abigail',
 'Absent Friends',
 'Paul Davis',
 'Jimmy Nail',
 'Yves Klein Blue',
 'Maria McKee',
 'Spectrum',
 'Frank Mills',
 'Yvonne Elliman',
 'Maxine Nightingale',
 'Glen Hansard',
 'Markéta Irglová',
 "The Mavis's",
 'The Stylistics',
 'August Alsina',
 'Rick Ross',
 'Ronin',
 'Mac Davis',
 'Andy C',
 'Fiora',
 'Dynoro',
 "Gigi D'Agostino",
 'Los Bravos',
 'Loon',
 'The Nashville Teens',
 'Gloria Loring',
 'Carl Anderson',
 'P.J. Proby',
 'Shakespears Sister',
 'Candice Alley',
 'Jubël',
 'NEIMY',
 'KYLE',
 'Das singende Krokodil vom Nil',
 'Tigerlily',
 'Nat Dunn',
 'M.P.D. Limited',
 'Leto',
 'Traveling Wilburys',
 'Frankee',
 'Dan Hartman',
 'Gummibär',
 'The Plastic Ono Band',
 'The String-A-Longs',
 'Pauline Henry',
 'Ronnie And The Hi-Lites',
 'Deorro',
 'Marlisa',
 'Kathryn',
 'Weddings Parties Anything',
 'Tony Joe White',
 'Ween',
 'Percy Faith',
 'CID',
 'Bahary',
 'The Flying Lizards',
 'Billy Paul',
 'Sirah',
 'Atlas Genius',
 'CDB',
 'TV Rock',
 'Dukes of Windsor',
 'Ace Cannon',
 'Tight Fit',
 'Joan Baez',
 'Gareth Gates',
 'Rebecca Ferguson',
 'Chad Kroeger',
 'Raspberries',
 'Hardwell',
 'Yall',
 'Gabriela Richardson',
 'Filter',
 'HRVY',
 'Larry Hall',
 'Mark Williams',
 'Ron Holden',
 'ELAZ',
 'Lee Marvin',
 'Nathaniel Rateliff & The Night Sweats',
 'The Panics',
 "Ol' Dirty Bastard",
 'Nate Ruess',
 'Acker Bilk',
 'Alias',
 'Saweetie',
 'The Crooklyn Clan',
 'Default',
 'Carolina Liar',
 'J Balvin',
 'Chaka Khan',
 'Nazareth',
 'Wild Cherry',
 'Simian Mobile Disco',
 'Mickie James',
 'Chapel Hart',
 'Zaheer',
 'Big Pig',
 'Sandie Shaw',
 'The Dave Brubeck Quartet',
 'Rise Against',
 'L D R U',
 'The Cookies',
 'Audioslave',
 'Agnes',
 'Emilio Pericoli',
 'Tommy Boyce',
 'Bobby Hart',
 'Steven Tyler',
 'John Ryan',
 'Yung Joc',
 'Candi Staton',
 'Lawrence Reynolds',
 'Bonnie Raitt',
 'Room 5',
 'Oliver Cheatham',
 'Hot Butter',
 'Chris Sebastian',
 'The Midnight Beast',
 'Dreamworld',
 'Ann Lee',
 'Metric',
 'Pauline Pantsdown',
 'John Phillips',
 'AronChupa',
 'Little Sis Nora',
 'Tony Bennett',
 'Will Smith introducing TRÂ-KNOX',
 'Traknox',
 'Ross D. Wylie',
 'Springwater',
 'Terry Jacks',
 'Russell Thompkins\\',
 'Jr.',
 'Deep Purple',
 'Mary Mary',
 'Rema',
 'Jewel Akens',
 'Claudine Clark',
 'Scott English',
 'Frank Ocean',
 'Paris Hilton',
 'Taco',
 'Dyo',
 'The Trinidad Singers',
 'Bloc Party',
 'The Young Rascals',
 'Kids In The Kitchen',
 'Last Dinosaurs',
 'The Coral',
 'Larry Finnegan',
 'Art Garfunkel',
 'The Firm',
 'Black',
 'Lou Bega',
 'Max Bygraves',
 'Wreckx-N-Effect',
 'Public Announcement',
 'Jamie N Commons',
 'Jolyon Petch',
 'Reigan',
 'Kate Alexa',
 'Lynsey De Paul',
 'LP',
 'John Parr',
 'Paul Lekakis',
 'Naeleck',
 'Near Mrs',
 't.A.T.u.',
 'Ian Dury & The Blockheads',
 'Astrid S',
 'Deborah Cox',
 'Hot Action Cop',
 'Hayley Warner',
 'Thelma Houston',
 'Bob Luman',
 'Burton Cummings',
 'Mississippi',
 'Ayah Marar',
 'Dennis Lloyd',
 'Zeek Power',
 'PnB Rock',
 'Travis McCoy',
 'Sgt. Barry Sadler',
 'The Griswolds',
 'Qwote',
 'Things Of Stone and Wood',
 'Love Affair',
 'The Equals',
 'Butthole Surfers',
 'Barbara Lynn',
 'The Glitter Band',
 'Merrilee Rush',
 'Kevin Parker',
 'The Tymes',
 'Franklin',
 'Supernaut',
 'Freedom Under XRay',
 'Choirboys',
 'Jeremy Jordan',
 'Duane Eddy',
 'Long John Baldry',
 'Russell Watson',
 'Drummond',
 'BROCKHAMPTON',
 'George Baker Selection',
 'Shane Codd',
 'Katy Tiz',
 'Hank Ballard & The Midnighters',
 'Squeeze',
 'Nena',
 'Janis Joplin',
 'StoneBridge',
 'Therese',
 'Yellowcard',
 'Matt Scullion',
 'DR.',
 'Kaelo Mula',
 'Big Steppa',
 'Sam The Sham & The Pharaohs',
 'Kenny Rogers with Dolly Parton',
 'Lene Lovich',
 'Andy Gibb',
 'Eric Burdon',
 'War',
 'SAFIA',
 'Cash Cash',
 'Kansas',
 'Vic Dana',
 'Phantom Planet',
 'Cheryl',
 'New Edition',
 'Denis Leary',
 'Berlin',
 'Sam Ryder',
 'Chocolate Starfish',
 'The Platters',
 'Jim Reeves',
 '"Weird Al" Yankovic',
 'Sleepy Brown',
 'Monty Python',
 'M',
 'Robin Scott',
 'Nick Launay',
 'Patrick Swayze Featuring Wendy Fraser',
 'Ferlin Husky',
 'Jackie Trent',
 'Tony Hatch',
 'Peta Morris',
 'The Motels',
 'Ian Dury',
 'The Blockheads',
 'Sly Fox',
 'Airrion Love',
 'Brendan Bowyer & The Royal Showband',
 'Master KG',
 'Nomcebo Zikode',
 'Stacey Q',
 'Treble Charger',
 'Martha and the Muffins',
 'The Honeycombs',
 "Bomfunk MC's",
 'KIAN',
 'Dannii',
 'The Marcels',
 'Chris Martin',
 'The Heights',
 'LCD',
 'Phil Seymour',
 'Gary Moore',
 'Kenny Nolan',
 'Mike Perry',
 'shy martin',
 'Denzal Park',
 'Orianthi',
 'Boogie Pimps',
 'YellaCatt',
 'Joey Dee & The Starliters',
 'Violent Soho',
 'Toni Fisher',
 'Maxwell',
 'Stills & Nash',
 'LA Vision',
 'Sister2sister',
 'Måneskin',
 'C. J. Johnson',
 'The Badloves',
 'Dane Rumble',
 'Ric Wake',
 'Bob Cadway',
 'The Last Goodnight',
 'Cat & Calmell',
 'Paul Hardcastle',
 'XTC',
 'The Jaynetts',
 'The Henchmen',
 'White Town',
 "The Go-Go's",
 'The Rascals',
 'K-Ci & JoJo',
 'Collette',
 'Skepta',
 'OMC',
 'Smokey Robinson & The Miracles',
 'Kele',
 'Dom Dolla',
 'GAYLE',
 'The Strokes',
 'Carole Bayer Sager',
 'P Jervier',
 'Steve Jervier',
 'Wales',
 'E.Y.C.',
 'The Mar-Keys',
 'Nino Tempo & April Stevens',
 'Timmy Trumpet',
 'Iron Maiden',
 'Millie Small',
 'Starley',
 'Jigsaw',
 'Da Hool',
 'Frankie Avalon',
 'Bob Evans',
 'The Murmaids',
 'Barrett Strong',
 'Young the Giant',
 'The Capris',
 'Laura Pausini',
 'Crazy Town',
 'Tex Morton',
 'Yvonne Fair',
 'High Contrast',
 'Billy Vera & The Beaters',
 'Boyce Avenue',
 'Phil Oakey',
 'Giorgio Moroder',
 'Shanks & Bigfoot',
 'Cinderella',
 'Gin Wigmore',
 'Percy Sledge',
 'Lisa Loeb & Nine Stories',
 'The Little Heroes',
 'James Freud',
 'Supergrass',
 'The Copperwine',
 'Fuel',
 'Jimmy Charles',
 'Emma Bunton',
 'Feist',
 'bbno$',
 'Rich Brian',
 'Teddy Geiger',
 'Ali',
 'Ryan Tedder',
 'Ruff Loaderz',
 'MFSB',
 '"Jesus Christ Superstar" 1992 Australian Cast',
 'Jon Stevens',
 'Kate Cebrano',
 'Mark Dinning',
 'R & J Stone',
 'Matter Of Mind',
 'Five Man Electrical Band',
 'Asaf Avidan & the Mojos',
 'CamelPhat',
 'The Rasmus',
 'Marcus Santoro',
 'DJ Fresh',
 'Sian Evans',
 'Strike',
 'Pixies',
 'Kaoma',
 'Pete Shelley',
 'Mike Curb Congregation',
 'The Ormsby Brothers',
 'Junkie XL',
 'Ian Carey Project',
 'Skip Marley',
 'Bruce Channel',
 'Jack Blanchard & Misty Morgan',
 'Misty Morgen',
 'Neal Slateford',
 'Nick Batt',
 'Tim Finn',
 'These Kids Wear Crowns',
 'Chrissie Hynde',
 'Highway to Hell',
 'Juelz Santana',
 "T'Pau",
 'Bobbi Martin',
 'Billy Swan',
 'The Boomtown Rats',
 'Lasgo',
 'Kareen Lomax',
 'Kaylee Bell',
 'Hot Chip',
 'The Tourists',
 'Mixed By: Mykaell Riley & Jeremy Allom',
 'Supercharge',
 'Elliphant',
 'Ben Harper And The Innocent Criminals',
 'Cage The Elephant',
 'Sugarland',
 'Serena Ryder',
 'Bent Fabricius-Bjerre',
 'Britney Holmes',
 'Peabo Bryson with Roberta Flack',
 'Mousse T.',
 "Hot 'N' Juicy",
 'Rayvon',
 'MK',
 'Beverlee',
 'Seany B',
 'Black Lace',
 'Buffalo Springfield',
 'Stephanie Mills',
 'Stereophonics',
 'Barenaked Ladies',
 'Ivan Gough',
 'Feenixpawl',
 'Georgi Kay',
 'Beck',
 'The Tony Rich Project',
 'Collett',
 'Willy William',
 'Rage Against The Machine',
 'Next',
 'Patti Smith',
 'Joey Dee',
 'The Starliters',
 'Donnie Brooks',
 'Trisha Yearwood',
 'XYLØ',
 'Barry Ryan',
 'Thandi Phoenix',
 'Lonnie Mack',
 'Shane Howard',
 'Jon Secada',
 'Barbara George',
 'Mimi Webb',
 'Simon Climie',
 'Groove Theory',
 'George Thorogood & The Destroyers',
 'Bill Blacks Combo',
 'Brad Paisley',
 'Lorne Greene',
 'Uncanny X-Men',
 'Robin S',
 'Motiv8',
 'Eric Hutchinson',
 'Faouzia',
 'Nea',
 'Elaine Paige',
 'Barbara Dickson',
 'Andy Black',
 'Juliet Simms',
 'FIFTY FIFTY',
 'Peggy March',
 'Harry Chapin',
 'Glades',
 'Future Humans',
 'The Ikettes',
 'Tom Robinson Band',
 'Dee Gees',
 'Krewella',
 'Phyllis Nelson',
 'Flux Pavilion',
 'A. Manetta',
 'Joel Turner',
 'Marina Eco',
 'Loona',
 'Mel',
 'Seeb',
 'George Jones',
 'Gerry Rafferty',
 'Ryan Riback',
 'A.L.T. And The Lost Civilization',
 'Sam And The Womp',
 'Tori Amos',
 'Brotherhood of Man',
 'Jake Reese',
 'Clodagh Rodgers',
 'Plumb',
 'We The Kings',
 'Ylvis',
 'Case',
 'Eurika',
 'Gregory Abbott',
 'Harpo',
 'Matoma',
 'Mike Waters',
 'Extreme',
 'Motor Ace',
 'Boris Dlugosch',
 'Michael Lange',
 'Charlee',
 'David Rose & His Orchestra',
 'Stevie Hoang',
 'The Atlantics',
 'Allan Sherman',
 'Andrew Stanley',
 'Matt Handles',
 'Plastic Bertrand',
 'Clarence "Frogman" Henry',
 'Dorothy Moore',
 'Big Brother & The Holding Company',
 'Interactive',
 'StarLab',
 'P-Money',
 'Steady Rollin',
 'Wilson Pickett',
 'The Marshall Tucker Band',
 'Matchbox',
 'Ted Mulry',
 'F.C.B',
 'Fragma',
 'Rudolph Toombs',
 'Duffy',
 'Shawn Colvin',
 'SWOOP',
 'Cliff Richard & The Drifters',
 'Linda McCartney',
 'Stars On 45',
 'Alison Moyet',
 'Hayden James',
 'The Funky Groove Connection',
 'Bob Lind',
 'M2M',
 'The Newbeats',
 'GROUPLOVE',
 'Jonathan "JR" Rotem',
 'Labrinth feat. Tinie Tempah',
 'Vic Reeves',
 'The Wonder Stuff',
 'XXXTENTACION',
 'Flight Facilities',
 'Bic Runga',
 'Archie Roach',
 'The Isley Brothers',
 'Adrian Lux',
 'Union J',
 'Junior Senior',
 'Rob Swire',
 'Bryson Tiller',
 'Louis Mattrs',
 'James Blundell',
 'Shanice',
 'Classified',
 'Phiness',
 'Mia Rodriguez',
 'Gilbert Bécaud',
 'Judy Stone',
 'Marlon Roudette',
 'KSI',
 'The Streets',
 'The Five Stairsteps',
 'Jack Ü',
 'The Lemonheads',
 'Huey Lewis',
 'Public Domain',
 'M People',
 'Damage',
 'The Love Unlimited Orchestra',
 'HVME',
 'Siedah Garrett',
 'Jaheim',
 'Chase Martin',
 'Jimmy & the Boys',
 'Wayne Newton',
 'Big Country',
 'The Safaris',
 'Feed Me',
 'Crystal Fighters',
 'Glass Tiger',
 'The Paris Sisters',
 'John Lloyd Young',
 'Breathe Carolina',
 'The Waterboys',
 'The First Class',
 'Jay Hardway',
 'Luude',
 'Billy Bland',
 'Josey Scott',
 'Daniel Johns',
 'Rush',
 'Tasmin Archer',
 'Nina Simone',
 'Rococo',
 'A*M*E',
 'Scooter',
 'Kilter',
 'Alvin Stardust',
 'C.C.S.',
 'Frida',
 'Moving Pictures',
 'Sammie',
 'Boy Matthews',
 'DeBarge',
 'Bodyrockers',
 'Bodeans',
 'The Simon Park Orchestra',
 'Esther and Abi Ofarim',
 'The Androids',
 'Freeez',
 'The Knack',
 'Little Eva',
 'Jimmie Rodgers',
 'Faithless',
 'Rollo Armstrong',
 'Sister Bliss',
 'Edwyn Collins',
 'Thierry Von Der Warth',
 'Jay Mason',
 'The Bonzo Dog Band',
 'Peach PRC',
 'Oliver Heldens',
 'Vula',
 'The Biz',
 'Chris Franklin',
 'The Kingsmen',
 'Fountains Of Wayne',
 'Daniel Caesar',
 'The Kingston Trio',
 'The Future Hit Makers',
 'Eliza Rose',
 'Interplanetary Criminal',
 'Creeds',
 'Zombie Nation',
 'Vandalism']

all_genres = [
 'dance',
 'hip hop',
 'pop',
 'rock',
 'classic',
 'folk',
 'punk',
 'singer-songwriter',
 'electronic',
 'indie',
 'r&b',
 'piano',
 'metal',
 'canadian',
 'rap',
 'alternative',
 'rock-and-roll',
 'disco',
 'glee',
 'reggae',
 'emo',
 'lounge',
 'country',
 'edm',
 'techno',
 'funk',
 'blues',
 'contemporary',
 'trap',
 'ska',
 'boy band',
 'lo-fi',
 'sad',
 'rave',
 'rhythm and blues',
 'comedy',
 'grunge',
 'gospel',
 'vocal harmony group',
 'acapella',
 'k-rap',
 'korean',
 'broadway',
 'soul',
 'instrumental',
 'christian',
 'opera',
 'k-pop',
 'parody',
 'soundtrack',
 'movie'
 ]

all_eras = [
  "2020s",
  "2010s",
  "2000s",
  "1990s",
  "1980s",
  "1970s"
]


